python:
  path: "/usr/bin/python3"
api_keys:
  OpenGWAS: "YOUR_OPENGWAS_TOKEN"
  LDlinkR: "YOUR_LDLINKR_TOKEN"

filters:
  p_value_common: 5e-08
  p_value_uncommon: 5e-08
  maf_common: 0.05
  maf_uncommon: 0.01
  pip_cutoff: 0.1
  abc_score_cutoff: 0.015
  INFO_cutoff: 0.82

GTEx:
  version: "gtex_v10"

phenotypes:
  - "gwas_1"

locus:
  Radius: 500000
